[package]
name = "memcache_protocol"
version = "0.1.0"
authors = ["Ben Evans <bevans@zendesk.com>"]

[dependencies]
nom = "^2.0"
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"